### ISSUE TITLE
Build shared libraries for gtkd-git

### ISSUE THREAD

**Issue by dsboger** [SShrike/pkgbuilds#1]
Hello! I'm the maintainer of terminix-git package and I'm working towards depending on gtkd-git. For that, it would be awesome if this package would generate shared libraries. The current PKGBUILD generates only static ones.

I've investigated a bit and managed to make a custom PKGBUILD that successfully builds and installs .so files. It is listed below. The `LDFLAGS='-L-ldl -m64 -defaultlib=:libphobos2.so'` is related to https://github.com/gtkd-developers/GtkD/issues/151 and I'm still trying to figure out.

Could you give it a look? Thanks!

```
pkgname=gtkd-git
pkgver=r1258.4b67777
pkgrel=1
pkgdesc='D binding and OO wrapper of GTK+'
url='http://gtkd.org'
options=('staticlibs')
license=('LGPL')
arch=('i686' 'x86_64')
provides=('gtkd')
conflicts=('gtkd')
depends=('libphobos2' 'gtk3')
makedepends=('dmd')
optdepends=('pango' 'atk' 'gdk-pixbuf2' 'gtksourceview3' 'gstreamer' 'vte3')
source=('git://github.com/gtkd-developers/GtkD.git')
md5sums=('SKIP')

pkgver() {
  cd GtkD
  echo r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)
}

build() {
  cd GtkD
  make LDFLAGS='-L-ldl -m64 -defaultlib=:libphobos2.so' all
}

package() {
  cd GtkD
  make prefix="/usr" DESTDIR="${pkgdir}/" install install-gstreamer install-vte \
    install-shared install-shared-gstreamer install-shared-vte
}
```

**Comment by SShrike** [comment]
Thanks for the issue! Unfortunately I'm away today (easter holiday), however once I get home I'll be glad to take a look!

**Comment by dsboger** [comment]
In case you may use my PKGBUILD as a template, I've made a typo. It's `libphobos` and not `libphobos2` in the depends array.

**Comment by dsboger** [comment]
As per https://github.com/gtkd-developers/GtkD/issues/151, `LDFLAGS` is set by `makepkg.conf`, but that default is not understood by `dmd`. I've solved the issue by building like follows:

```
build() {
  cd GtkD
  LDFLAGS=''
  make all
}
```

**Comment by dsboger** [comment]
Have you taken a look at it? Any thoughts? Would you accept a PR for that?

**Comment by SShrike** [comment]
Sorry about the wait, it's been a very busy week. I could add you as a co-maintainer on the AUR if you'd like, your changes seem fine :)

**Comment by SShrike** [comment]
I've updated `gtkd` and `gtkd-git`, so everything should be working now.

**Comment by dsboger** [comment]
Thanks a lot! I would not mind become a co-maintainer if you are OK with that.

I've noticed you changed from dmd to ldc compiler mentioning that it is required for shared libs. I could build the shared libs fine with dmd before. Is there a specific reason for using ldc, bugs in dmd and gdc, for example? Its not like I prefer dmd, I'm just curious. I've read somewhere [1] that they are not ABI-compatible, so tha would mean that I'd have to build terminix with ldc also?

[1] https://wiki.gentoo.org/wiki/Dlang#Why_are_D_libraries_not_installed_in_their_default_locations.3F

**Comment by SShrike** [comment]
From the GtkD README:
```
 * shared = build gtkd and gtkd-sourceview as shared libraries.
            This currently only works with LDC.
```

It seems that while everything would compile fine, the tests would fail unless you use LDC.

**Comment by dsboger** [comment]
Same username as here: dsboger

**Comment by SShrike** [comment]
I've gone ahead and made you a co-maintainer of `gtkd` and `gtkd-git`. If you can, try and run any changes through me and try to keep the changes the same between each package. Ideally the only difference should be that the `-git` package is built from the latest upstream revision.

**Comment by dsboger** [comment]
As per https://github.com/gtkd-developers/GtkD/commit/7a4b7d73916c3da1828643f7179172f9b73dcfcd and https://github.com/gtkd-developers/GtkD/issues/151#issuecomment-205509078 it seems that building shared libraries should work fine with both `ldc` and `dmd`. Devs are not sure about `gdc`, though. 

It would be nice to depend on `d-compiler`, provided by any D compiler. I cannot go as far as testing `gdc`, but we could do that tentatively and wait for user feedback, WDYT?

**Comment by dsboger** [comment]
I'd also like to change the version number scheme to follow this recommendation: https://wiki.archlinux.org/index.php/VCS_package_guidelines#Git. This way it would be possible for gtkd-git to provide gtkd even when deps are in the format "gtkd>=3.3.0".

**Comment by SShrike** [comment]
> It would be nice to depend on d-compiler, provided by any D compiler. I cannot go as far as testing gdc, but we could do that tentatively and wait for user feedback, WDYT?

Good idea, I was not aware of `d-compiler`. Since it seems DMD does indeed work I don't see why we shouldn't support both. Still not sure why the tests failed with DMD though, I'll have to look into it and disable the tests in the meantime.

> I'd also like to change the version number scheme to follow this recommendation: https://wiki.archlinux.org/index.php/VCS_package_guidelines#Git. This way it would be possible for gtkd-git to provide gtkd even when deps are in the format "gtkd>=3.3.0".

Sounds good, this is something I've thought about doing for a while.

**Comment by SShrike** [comment]
Lets continue the discussion in the [Gitter room](https://gitter.im/SShrike/pkgbuilds) I've made.

**Comment by SShrike** [comment]
@dsboger If we are to makedepend on `d-compiler`, what is the dependency for the standard library? We wouldn't have to depend on a D stdlib if it was statically compiled, but since the shared libraries are now built we have to depend on a stdlib.

**Comment by SShrike** [comment]
Illustrating the dependencies:

```
( ⌁ ) D ) P ) p ) gtkd-git ) ldd /usr/lib/libgtkd-3.so                             21:19:36 ≡ 1
	linux-vdso.so.1 (0x00007ffedddeb000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f44aa5fe000)
	libphobos2-ldc.so.68 => /usr/lib/libphobos2-ldc.so.68 (0x00007f44a9f94000)
	libdruntime-ldc.so.68 => /usr/lib/libdruntime-ldc.so.68 (0x00007f44a9ca7000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f44a9a9e000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f44a9881000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f44a957c000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f44a91da000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x000055c5613cc000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f44a8fc4000)
```

```
( ⌁ ) D ) P ) p ) gtkd-git ) sudo pkgfile -l liblphobos                               21:21:48 
community/liblphobos	/usr/
community/liblphobos	/usr/lib/
community/liblphobos	/usr/lib/libldruntime-debug.so
community/liblphobos	/usr/lib/libldruntime.so
community/liblphobos	/usr/lib/liblphobos2-debug.so
community/liblphobos	/usr/lib/liblphobos2.so
community/liblphobos	/usr/share/
community/liblphobos	/usr/share/licenses/
community/liblphobos	/usr/share/licenses/liblphobos/
community/liblphobos	/usr/share/licenses/liblphobos/LICENSE
```

**Comment by dsboger** [comment]
I've studied the situation with D stdlib in the official repos and it seems a bit messy:

- O the `dmd` side, there are 2 packages: `libphobos-devel` (static libs + sources, `dmd` depends on it directly) provides `d-runtime` and `d-stdlib`; `libphobos` (shared libs only) does not provide any "symbolic" pacakge
- On the `ldc` side, there is only 1 package: `liblphobos` (shared libs only) provides no "symbolic" package
- On the `gdc` side, there is only 1 package: `libgphobos-devel` (static libs + sources) provides both `d-runtime` and `d-stdlib`

To solve that we would have to talk to the maintainer of the official packages and/or provide a few others ourselves to fill the gaps. I would prefer that the `-devel` packages be merged with the corresponding shared libs (like e.g. `glibc` does) in the non-splitting spirit of arch. That together with proper `provides` would make our case much simpler.

**Comment by SShrike** [comment]
I had a poke around after I commented, and it was messy indeed.

We'll have to file an issue and see if they could merge some of the
packages like you suggested.

**Comment by dsboger** [comment]
Filed the issue https://bugs.archlinux.org/task/48830.

**Comment by dsboger** [comment]
Given the discussions and clarifications of issue https://bugs.archlinux.org/task/48830, maybe a good compromise is to provide different packages for different compilers, i.e. `gtkd-dmd` and `gtkd-ldc` with dynamic libs, `gtkd-gdc` with static libs. One of them could be named `gtkd` as the default (probably `gtkd-ldc`, as it is already the `gtkd`.

If you agree, I'll create and maintain `gtkd-dmd` and `gtkd-dmd-git`, as those are the ones I'm most interested in (`terminix` is compiled/tested upstream with `dmd` only).

**Comment by SShrike** [comment]
Sounds cool, I had an idea like that originally :+1:
